### ISSUE TITLE
Napisanie README

### ISSUE THREAD

**Issue by Nircek** [Nircek/pikna-mapa#1]

**Comment by MarszolekM** [comment]
Nie rozumiem o co chodzi z tym README, mógłbyś mi wytłumaczyć?

**Comment by Nircek** [comment]
@MarszolekM
README ogólnie zawiera informacje o danym programie. Jak nazwa wskazuje użytkownik, któwy wejdzie w posiadanie danego programu i/lub jego kodu źródłowego powinien się zapoznać z jego treścią. Często umieszcza się tam jakieś licencje, żeby każdy czuł się poinformowany na jakich warunkach może korzystać z niego. W naszym przypadku mamy do tego osoby plik [LICENSE](//github.com/Nircek/pikna-mapa/blob/master/LICENSE).

Poza tym na GitHubie plik README automatycznie wyświetla się na stronie projektu (tylko musi istnieć). Mogę posłużyć się tutaj przykładem z mojego [labiryntu](//github.com/ZayeBeast/labirynt):
![image](https://user-images.githubusercontent.com/26528678/66235260-fac07580-e6ef-11e9-9924-5193fbfea2a6.png)

Także można tam umieścić informację o autorach, jakiś dłuższy opis co zrobiliśmy, po co, ile nam to zajęło, czego się nauczyliśmy przez to i takie tam. Może tam być dosłownie wszystko czym więcej tym lepiej (teoretycznie).

**Comment by Nircek** [comment]
Poza tym nie bez powodu README ma rozszerzenie `.md`. Jest to skrót od MarkDown, którego można używać w takich plikach. Ogólnie chodzi o to, że przez dodawanie konkretnych sekwencji znaków możemy wymusić renderowanie (składanie) tekstu w odpowiedni sposób.
# dla przykładu tutaj jest nagłówek
> a tu to powinno się wyświetlać jako cytat

| można | też |
| --- | --- |
| robić jakieś | tabelki |

Jest tego mnóstwo także do takich *bardzo* podstawowych zastosowań odsyłam [tutaj](https://guides.github.com/features/mastering-markdown/), ale polecam też wygooglać różne inne ciekawe rzeczy.

**Comment by Kapibara-milosc** [comment]
Do napisania README można już użyć listy autorów  z #17

**Comment by Nircek** [comment]
Zrobione w #18.
