### ISSUE TITLE
Dokładność i sposób przedstawienia lokalizacji.

### ISSUE THREAD

**Issue by Marwyk2003** [Nircek/pikna-mapa#11]
Mam pomysł by zaznaczać miejsce naszego zamieszkania obszarem, czyli kwadratem pokazujący w przybliżeniu tę lokalizację. 
Jak duży powinien on być i jak bardzo powinien być niedokładny (Jego środek nie powinien być idealnie w dobrym miejscu)?

**Comment by Nircek** [comment]
Proponuję użyć systemu wykorzystywanego przez radioamatorów, czyli [QTH locator](https://pl.wikipedia.org/wiki/QTH_locator). Optymalnie myślę, że będzie do 4. iteracji, czyli na przykład `JO90kg90`. Jest mnóstwo interaktywnych map korzystających z tego systemu, na przykład [ta](http://ostol.pl/mapa-qth-lokatorow). Rozwiązuje to też problem z niedokładnością, ani środkiem na środku, bo mapę świata dzielimy na siatkę kwadratów i podajemy po prostu identyfikator danego kwadratu. Nie musimy nic losować, po prostu korzystamy z gotowego systemu.

**Comment by Nircek** [comment]
W zasadzie to to jest duplikat #9. No ale cóż. To zamknę #9 z powodu bycia duplikatem. :stuck_out_tongue_winking_eye:
