### ISSUE TITLE
Autorzy

### ISSUE THREAD

**Issue by Kapibara-milosc** [Nircek/pikna-mapa#17]

**Comment by Nircek** [comment]
@Monika452 @MichalTheProgrammer wstawić do stopki
`aleksandra2505, AW, Crackhoff, Kapibara-milosc, MarszolekM, marwyk2003, masochista-biblista, MichalTheProgrammer, miloszwasacz, Monika452, ToJaKuba, Nircek © 2019`

**Comment by Nircek** [comment]
Po spisaniu listy autorów będzie można ją wykorzystać w #1. @Kapibara-milosc możesz tutaj wkleić całą listę.

**Comment by Kapibara-milosc** [comment]
[@aleksandra2505](https://github.com/aleksandra2505) - zaprojektowanie struktury i wyglądu strony
AW - przepisanie danych uczniów
[@Crackhoff](https://github.com/Crackhoff) - zaprogramowanie funkcji zajmującej się Data Management 
[@Kapibara-milosc](https://github.com/Kapibara-milosc) - zebranie danych od członków projektu 
[@MarszolekM](https://github.com/MarszolekM) - zebranie informacji dotyczących RODO
[@Marwyk2003](https://github.com/Marwyk2003) - sformatowanie danych do formatu JSON
[@masochista-biblista](https://github.com/masochista-biblista) - przepisanie danych uczniów  
[@MichalTheProgrammer](https://github.com/MichalTheProgrammer) - stworzenie strony w HTML 
[@miloszwasacz](https://github.com/miloszwasacz) - zaprojektowanie oraz wykonanie logo
[@Monika452](https://github.com/Monika452) - stworzenie strony w HTML
[@Nircek](https://github.com/Nircek) - główny koordynator projektu, stworzenie strony w HTML
[@ToJaKuba](https://github.com/ToJaKuba) - zebranie danych od uczniów
