### ISSUE TITLE
Zebranie danych

### ISSUE THREAD

**Issue by Nircek** [Nircek/pikna-mapa#2]
Proszę nie zamieszczać w żadnej formie zebranych danych na GitHubie. Wszystko przesyłać między sobą i ostateczną wersję wysłać mi.

**Comment by Nircek** [comment]
Zgodnie z #3 i #11 należałoby zebrać dane z uwzględnieniem QTH locatora. Mianowicie niektóre osoby mogą mieć problem z podaniem swojej dokładnej lokalizacji, także po otrzymaniu od nich informacji o miejscu zamieszkania (np. Kochłowice) należałoby dopytać się w którym kwadracie (prostokącie) mieszkają. W tym celu najprościej jest wejść na [tę stronę](https://www.egloff.eu/googlemap_v3/carto.php), zrobić screenshota okolicy i zapytać się, w którym kwadracie mieszkają. Przykładowo dla Kochłowic:
![image](https://user-images.githubusercontent.com/26528678/66720258-c2f5b400-edfa-11e9-8abf-f3be7fe58fbd.png)
Lub po prostu podesłać danej osobie linka do tej strony. Lokalizacja powinna być do 4 iteracji, czyli powinna mieć 8 znaków (np. JO90kg90)

**Comment by ToJaKuba** [comment]
Taki o wzór wiadomości zrobiłem co myślicie?
Cześć, jak wiesz lub może nie część naszej klasy wzięła się za zrobienie projektu(zebranie geolokalizacji zamieszkania uczniów z naszej klasy i przedstawienie  jej w formie interaktywnej mapy). I tutaj pojawia się pytanie do ciebie czy chcesz znalesc się na tej mapie, lub masz coś przeciw. Jeśli wyrazisz taką ochotę to możemy zapisać twoje imię i nazwisko jako inicjaly lub imię i pierwsza literę nazwiska. Twój dokładny adres nie będzie podany, zaznaczymy twoją lokalizację w prostkotach takich jak na tej stronie https://github.com/Nircek/pikna-mapa/issues/2#issuecomment-541446435
Możesz podać mi swój adres a ja odszukam prostokąt, a jeśli masz coś przeciw możesz sama to zrobić i podać mi nazwę tego prostokątu która znajduje się w lewym górnym rogu każdego obszaru (ta opcja była by dużo lepsza gdyż muszę to zrobić z 34 osobami :p)

**Comment by Nircek** [comment]
Niestety nie możemy wszystkich zamieścić z inicjałami, bo niektóre kolidują ze sobą. Także przychodzi mi tylko na myśl, że niektórym osobom nie damy możliwości wyboru opcji z inicjałami. :stuck_out_tongue:
Co do samego tekstu to trochę nie podoba mi się "pytanie do ciebie czy chcesz znalesc się na tej mapie". W sensie to brzmi jak możliwość nieuczestnictwa, która teoretycznie jest możliwa, ale bardzo tego nie chcemy. Także jakbyś napisał to inaczej albo ewentualnie kontynuował rozmowę mimo braku odpowiedzi lub odpowiedzi negatywnej. W sumie jak ktoś nie da swoich danych to i tak specjalnie do niego napiszę, także jak chcesz to zostaw.
Można zamiast dawać wybór to po prostu zamieścić imię i pierwszą literę nazwiska w razie potrzeby.
