### ISSUE TITLE
Ustalenie formatu danych

### ISSUE THREAD

**Issue by Nircek** [Nircek/pikna-mapa#3]
JSON do JSa będzie lepszy niż XML :smiley:

**Comment by Nircek** [comment]
Znalazłem coś takiego jak GeoJSON. Fajnie by było tego użyć, bo nie musimy wymyślać własnego standardu, tylko korzystamy z wymyślonego.

**Comment by Nircek** [comment]
@Marwyk2003 przejrzyj [przykład od Leafleta](https://leafletjs.com/examples/geojson/) i zrób coś na tej bazie, żeby się zgadzało.

**Comment by Marwyk2003** [comment]
**Taki będzie format danych w pliku .json:**
```json
{
  "type":"FeatureCollection",
  "features":[
    {
      "type":"Feature",
      "geometry":{
        "type":"Point",
        "coordinates":[
          0.0,
          0.0
        ]
      },
      "properties":{
        "Id":"Numer w dzienniku",
        "FirstName":"Imie",
        "LastNameInitial":"Nazwisko",
        "QthLocator":"nazwa locatora"
      }
    },
    {
      "type":"Feature",
      "geometry":{
        "type":"Point",
        "coordinates":[
          0.0,
          0.5
        ]
      },
      "properties":{
        "Id":"30",
        "FirstName":"Marcin",
        "LastNameInitial":"W.",
        "QthLocator":""
      }
    }
  ]
}
```

**Kolejność w "coordinates": [długość geograficzna, szerokość geograficzna]**

Aby dodać kolejną osobę należy przekopiować ten fragment`:
```json
{
  "type":"Feature",
  "geometry":{
    "type":"Point",
    "coordinates":[
      0.0,
      0.0
    ]
  },
  "properties":{
    "Id":"Numer w dzienniku",
    "FirstName":"Imie",
    "LastNameInitial":"Nazwisko",
    "QthLocator":"nazwa locatora"
  }
}
```
**Należy też dodać przecinek w przedostatniej klamrze, która zamyka "features"**

**Comment by Nircek** [comment]
@Marwyk2003 Może lepiej zamiast bawić się potem w JSem w dodawanie klikalnych markerów to dodać do properties `popupContent` zamiast `FirstName`, `LastNameInitial` i `QthLocator`.
Można też dodać w JSie funkcję zgodną z [tym](https://gis.stackexchange.com/a/229743). Co myślisz?

**Comment by Marwyk2003** [comment]
Przerobiłem już format, teraz properties wygldają tak:
```json
"properties": {
            "popupContent": "<center>Id <b>FirstName LastNameInitial</b><br>QthLocator</center>"
         }
```
