### ISSUE TITLE
Narysować szkic wyglądu strony

### ISSUE THREAD

**Issue by Nircek** [Nircek/pikna-mapa#4]
Można zamieszczać swoje propozycje tutaj

**Comment by Monika452** [comment]
![szkic strony](https://user-images.githubusercontent.com/55319526/66742328-b2375380-ee77-11e9-8a0f-8ff4423af397.png)

**Comment by Nircek** [comment]
Jeżeli chcielibyśmy robić mobilną wersję strony to dobrze by było, żeby mapa zajmowała całą dostępną przestrzeń. Albo chociaż większość z małym logiem i tytułem. Poza tym musiałaby być dopasowana do wielkości urządzenia.

**Comment by Nircek** [comment]
Na stronie ogólnie ma być logo, tytuł, może jakiś opis jak ktoś coś napisze, sama mapa i może jakaś stopka na dole z copyrightem. Jakieś proporcje, kolory wskazane. Do tego można od razu pisać wszystko w CSSie jak ktoś zna, bo i tak potem ktoś to będzie musiał na CSSa przepisać.

**Comment by Monika452** [comment]
![001](https://user-images.githubusercontent.com/55319526/67690956-155bd680-f99e-11e9-953f-3fe9516c1271.jpg)

**Comment by Nircek** [comment]
W sumie to szkic jest narysowany. Do zamknięcia.
