### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Nircek** [Nircek/pikna-mapa#5]
Wymyśleć logo

**Comment by Nircek** [comment]
Mój pierwszy lepszy pomysł to wzięcie tekstury mapy z Minecrafta
![tekstura mapy z MC](https://gamepedia.cursecdn.com/minecraft_pl_gamepedia/c/c6/Grid_Mapa.png?version=06ce99ef79461fac73469a140e1a8bb6)

**Comment by MarszolekM** [comment]
Można dać na logo mapę (Katowic i okolic) w kształcie pika karcianego.

**Comment by miloszwasacz** [comment]
Gdzie mamy wrzucać ewentualnie projekty logo?

**Comment by Nircek** [comment]
@miloszwasacz może być bezpośrednio tutaj
a jak nie chcecie tutaj to możecie w chmurę wrzucić i podlinkować tu jakoś

**Comment by Nircek** [comment]
@MarszolekM @miloszwasacz przy okazji przypominam, że jeżeli chcecie się zajmować jakimś issuesem to polecam kliknąć "assign yourself" na górze po prawej
![image](https://user-images.githubusercontent.com/26528678/66234889-2000b400-e6ef-11e9-8c3c-1208393c3ba8.png)

**Comment by Nircek** [comment]
> Można dać na logo mapę (Katowic i okolic) w kształcie pika karcianego.

@MarszolekM spróbujesz coś takiego stworzyć?

**Comment by miloszwasacz** [comment]
Zrobiłem pierwszy projekt i czekam na feedback.
![PIKna mapa](https://user-images.githubusercontent.com/48798388/66255512-81bf2d80-e784-11e9-889e-d8d8df15b13b.png)

**Comment by miloszwasacz** [comment]
Wersja 2:
- mniejsze znaczki pika
- zakręty drogi są pod lepszymi kątami
![PIKna mapa v2](https://user-images.githubusercontent.com/48798388/66258143-ed63c380-e7a1-11e9-8a5a-fab66e7493b3.png)

**Comment by miloszwasacz** [comment]
Ostateczne logo w wersji wektorowej i rastrowej
[PIKna mapa logo.zip](https://github.com/Nircek/pikna-mapa/files/3693533/PIKna.mapa.logo.zip)
