### ISSUE TITLE
Wybrać główną bibliotekę

### ISSUE THREAD

**Issue by Nircek** [Nircek/pikna-mapa#6]
Pierwsze lepsze:
[LeafLetJS](https://leafletjs.com/)
[MapTiler](https://cloud.maptiler.com/maps/streets/)

**Comment by Nircek** [comment]
@GummyBear45 mi osobiście bardziej przypadł do gustu leaflet, ale sam zobacz, co wolisz

**Comment by GummyBear45** [comment]
jak dla mnie tez leaflet bo za kod z maptilera do mobilek trzeba placic i nie znalazlem dokumentacji, a przy leaflecie wszystko jest o d razu podane a dokumentacja wydaje sie być czytelna

**Comment by Nircek** [comment]
no i git, issue do zamknięcia, bo biblioteka wybrana :tada:
