### ISSUE TITLE
RODO

### ISSUE THREAD

**Issue by Nircek** [Nircek/pikna-mapa#8]
Dowiedzieć się co z RODO, czy musimy jakieś druczki pisać, czy zaokrąglenie lokalizacji do 500m jest wystarczające, czy robimy to na imionach i paru pierwszych literach nazwiska itd...

**Comment by MarszolekM** [comment]
Jeżeli chodzi o ewentualność druczków i zgód to one będą musiały być do rodziców, a nie uczniów, ponieważ my nie możemy handlować swoimi danymi. Prawnie nie są nasze

**Comment by MarszolekM** [comment]
Jeżeli chodzi o ewentualność druczków i zgód to one będą musiały być do rodziców, a nie uczniów, ponieważ my nie możemy handlować swoimi danymi. Prawnie nie są nasze

**Comment by Nircek** [comment]
@MarszolekM 
Dobrzy byłoby dać jakieś źródła, ale to już taki mój kaprys. W każdym razie co sugerujesz? Lepiej chyba napisać jakiś "druczek" i poinformować wszystkich, co mamy zamiar z tym zrobić (bez prawnych kwestii) niż nie pisać nic i po prostu wziąć.

**Comment by MarszolekM** [comment]
Nie wiem za bardzo na czym będzie polegało szyfrowanie tych danych (w jakim kraju będą przechowywane) i kto będzie ich właścicielem. Bo zapiszemy to na jakiejś chmurze, a ona ma gdzieś serwer więc tak de facto ten serwer nie jest nasz więc dane też już nie są pod naszą kontrolą.
Musiałabym doszperać, ale poinformowanie nieletnich co zrobimy z ich danymi bez zgody ich rodziców nie ma sensu, ponieważ dane nieletnich nie są ich własnością. Albo pytamy rodziców, albo robimy to bez zgody i tyle.
Moglibyśmy przechowywać te dane przez czas określony, na potrzeby projektu, a potem np. 1 stycznia zniknęły by i nikt by już nie miał do nich dostępu. 
Jeżeli byśmy robili zgodę to trzeba by było uwzględnić jak długo przechowujemy, do jakich celów i kto będzie miał do nich dostęp.
Poczytam jutro dokładnie to RODO i postaram się napisać jakieś dokładniejsze rzeczy. Na razie to jest mój wywód na temat tego co słyszałam o Rodo od mamy nauczycielki oraz co zawsze pisze na zgodach o RODO. ;-)

**Comment by Nircek** [comment]
Trzeba też zaznaczyć, że nie jesteśmy żadną firmą i nie "sprzedajemy" tych danych (bo dajemy je za darmo :laughing:).

Co do tego, że jeżeli przechowujemy w chmurze to nie mamy dostępu do danych to masz rację.
Przechowywane dane w chmurze pewnie gdzieś się zindeksują i w jakichś archiwach mogą zostać zachowane, także nie ma czegoś takiego jak czas określony. Ale możnaby całą stronę hostować w chmurze (przez GitHuba), a same dane umieścić na własnym serwerze. Konkretnie mam na myśli własny tablet, bo teoretycznie nawet gdybyśmy kupili VPS (ekhem @GummyBear45) to teoretycznie też nie mamy fizycznego dostępu do dysku, a na swoim tablecie mam i jestem w stanie zrobić z tym wszystko.

Także dane mogą zniknąć po prosto w pewnym momencie, oczywiście w okresie gdy będą dostępne ktoś może je przechwycić, czyli pobrać po prostu. Ale potem już z mojego serwera znkiną na zawsze. Można je zaszyfrować, ale można (też lub zamiast szyfrowania) ustalić hasło potrzebne do pobrania ich. Wtedy będziemy pewni, że żaden Google przez przypadek tego nie zindeksuje.

Poza tym wydaje mi się, że pewne dane nie są danymi osobowymi i nie powinny podlegać RODO, co należałoby też sprawdzić. W sensie zamiast zastanawiać się jak prawnie operować na danych osobowych, można się zastanowić jak ominąć dane osobowe. Przykładem może być użycie pseudonimów i/lub pominięcie nazwisk albo zaokrąglenie lokalizacji do 500m albo kilometra albo 10 km. Wydaje mi się, że to już nie są dane osobowe, bo tym sposobem stwierdzenie, że Jan Kowalski mieszka w Katowicach byłoby danymi osobowymi.

**Comment by MarszolekM** [comment]
Jeżeli chodzi o RODO to mam odpowiedź:
Jeżeli użyjemy INICJAŁÓW lub czegoś w ten deseń, za adres damy tylko ULICĘ I MIASTO lub to zaokrąglenie do 500 m i będzie to bez zdjęcia(osoby) to to nie są dane osobowe i nie potrzebujemy na to zgody. Wtedy nawet nie trzeba kodować, bo nie możliwe jest znalezienie osoby.
Np. MM ul.Adamskiego Imielin nawet jeżeli dopiszesz, że uczę się w Piku to szkoła strzeże moich danych i znalezienie mnie jest bardzo trudne.

**Comment by Nircek** [comment]
No i git. Teraz w razie czego mam pełną odpowiedź, Ty wiesz od kogo masz taką informację, także w najgorszym wypadku mamy argument, że zostaliśmy wprowadzeni w błąd. I miejmy nadzieję, że wszystko będzie zgodnie z prawem.

Dzięki :tada:

Jakby ktoś chciał coś powiedzieć w tej kwestii to zamknięcia wcale nie znaczy braku możliwości komentowania

**Comment by Nircek** [comment]
@MarszolekM a imię i pierwsza litera nazwiska, jeżeli jest potrzebna do rozróżnienia osoby, przejdzie?

**Comment by MarszolekM** [comment]
Myślę, że tak. Na podstawie tego Janusz z Warszawy nie zidentyfikuje człowieka.
